import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "@/styles/globals.css";
import { getServerSession } from "next-auth";
import AuthSessionProvider from "@/components/SessionProvider";
import authOptions from "@/app/api/auth/[...nextauth]/authOptions";
import { Header } from "@/components/Header";
import Providers from "./providers";

// const inter = Inter({ subsets: ["latin"] });
const outfit = Outfit({ subsets: ["latin"] });
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
    modal,
}: Readonly<{
    children: React.ReactNode;
    modal: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <AuthSessionProvider session={session}>
                <body className={outfit.className}>
                    <Providers>
                        <div className="flex flex-col items-center min-h-screen antialiased overflow-hidden">
                            <Header />
                            <main className="mt-16 overflow-hidden">
                                {children}
                                <div id="navbar-root" />
                            </main>
                        </div>
                        {modal}
                        <div id="modal-root" />
                        <div id="search-root" />
                    </Providers>
                </body>
            </AuthSessionProvider>
        </html>
    );
}
